services:
  # Backend API service
  - type: web
    name: chatbot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend static site
  - type: web
    name: chatbot-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://chatbot-backend.onrender.com 